# -*- coding: utf-8 -*-
"""Movie Recomendation System (Content Based) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OGTm5ARr_zKNSfvxd1bvaES74D5-QOg
"""

import pandas as pd

movies = pd.read_csv("tmdb_5000_movies.csv")
print(movies.to_string())

movies.head()

credits = pd.read_csv("tmdb_5000_credits.csv")
credits.head()

movies.shape

credits.shape

movies.info()

credits.info()

"""**Merge the Two DataSets**"""

movies = movies.merge(credits, on='title')

movies.head(1)

# genre
# movie_id
# keywords
# title
# overview
# release date
# cast
# crew

movies = movies[['movie_id','keywords','title','overview','genres','cast','crew']]

movies.head(2)

movies.isnull().sum()

movies.shape

movies.duplicated().sum()

movies.dropna(inplace = True)

movies.shape

movies.duplicated().sum()

import ast
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'].lower())
  return L

movies['genres'] = movies['genres'].apply(convert)

movies['keywords']= movies['keywords'].apply(convert)

def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'].lower())
      counter += 1
    else:
      break
  return L

movies['cast'] = movies['cast'].apply(convert3)

def convert4(obj):
  L = []
  for i in ast.literal_eval(obj):
    if  i['job'] == 'Director':
      L.append(i['name'].lower())
      break
  return L

movies['crew'] = movies['crew'].apply(convert4)

movies['overview'] =  movies['overview'].apply(lambda x:x.split())

movies.head(1)

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head(1)

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

new_df = movies[['movie_id','title','tags']]

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df.head(2)

new_df['tags'][0]

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df.head(1)

new_df['tags'][0]

new_df['tags'][1]

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors[0]

import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(vectors)

similarity = cosine_similarity(vectors)
# diagonal always once

sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)
  return

recommend('Avatar')

